const products = [
  {
    id: 1,
    name: "Nebula X Pro Earbuds",
    category: "Wireless Headphones & Audio",
    price: 149,
    compareAtPrice: 189,
    rating: 0,
    reviews: 0,
    badge: "Best Seller",
    stock: 16,
    serialNumber: "MC-AUD-2101",
    illustration: "audio",
    palette: {
      panel: "from-cyan-500/18 via-slate-950 to-slate-900",
      glow: "bg-cyan-400/20",
      accent: "text-cyan-300",
      border: "border-cyan-400/20",
    },
    variants: [
      { id: "obsidian", name: "Obsidian Black", swatch: "bg-zinc-900", accent: "bg-cyan-300" },
      { id: "frost", name: "Frost Silver", swatch: "bg-slate-300", accent: "bg-sky-200" },
      { id: "violet", name: "Pulse Violet", swatch: "bg-violet-400", accent: "bg-violet-300" },
    ],
    collections: ["featured", "best-sellers", "new-arrivals", "audio", "trending"],
    tagline: "Adaptive noise cancelling earbuds for commutes, meetings, and late-night gaming.",
    description:
      "Nebula X Pro delivers low-latency wireless audio, adaptive noise control, and a sculpted fit that stays comfortable all day. The charging case supports fast top-ups and a matte finish that feels premium in hand.",
    highlights: ["48-hour battery with case", "Dual-device Bluetooth switching", "Low-latency game mode"],
    specs: {
      Drivers: "11mm graphene dynamic drivers",
      Connectivity: "Bluetooth 5.4",
      Battery: "8 hours + 40 hours with case",
      Charging: "USB-C and wireless",
      WaterResistance: "IPX5 splash resistance",
    },
    advisory: "Enable game mode before competitive sessions for the lowest possible latency.",
    delivery: "Ships in 24 hours",
    reviewsList: [],
  },
  {
    id: 2,
    name: "VoltGrid GaN Charging Hub",
    category: "Mobile Accessories",
    price: 89,
    compareAtPrice: 109,
    rating: 0,
    reviews: 0,
    badge: "Flash Deal",
    stock: 11,
    serialNumber: "MC-MOB-3892",
    illustration: "charging",
    palette: {
      panel: "from-amber-400/16 via-slate-950 to-slate-900",
      glow: "bg-amber-300/20",
      accent: "text-amber-300",
      border: "border-amber-300/20",
    },
    variants: [
      { id: "sand", name: "Arctic Sand", swatch: "bg-stone-300", accent: "bg-amber-300" },
      { id: "black", name: "Stealth Black", swatch: "bg-zinc-900", accent: "bg-orange-300" },
    ],
    collections: ["featured", "flash-deals", "mobile", "smart-gadgets"],
    tagline: "A compact 140W desktop charger that cleans up your entire setup.",
    description:
      "VoltGrid powers laptops, tablets, phones, and creator gear from a single sculpted aluminum hub. Smart power allocation keeps charging fast while the low-profile design sits neatly beside your monitor stand.",
    highlights: ["Three USB-C ports + one USB-A", "140W peak output", "Cool-running GaN core"],
    specs: {
      Output: "140W total power",
      Ports: "3 x USB-C, 1 x USB-A",
      Material: "Milled aluminum shell",
      Safety: "Temperature and surge protection",
      Cable: "2m braided AC cable",
    },
    advisory: "Use the included cable for best performance with high-power laptops.",
    delivery: "Flash deal ends tonight",
    reviewsList: [],
  },
  {
    id: 3,
    name: "Aether Mechanical 75",
    category: "Gaming Accessories",
    price: 179,
    compareAtPrice: 219,
    rating: 0,
    reviews: 0,
    badge: "Trending",
    stock: 9,
    serialNumber: "MC-GAM-7505",
    illustration: "keyboard",
    palette: {
      panel: "from-violet-500/18 via-slate-950 to-slate-900",
      glow: "bg-violet-400/20",
      accent: "text-violet-300",
      border: "border-violet-400/20",
    },
    variants: [
      { id: "graphite", name: "Graphite RGB", swatch: "bg-zinc-800", accent: "bg-violet-300" },
      { id: "white", name: "Cloud White", swatch: "bg-zinc-200", accent: "bg-fuchsia-300" },
      { id: "navy", name: "Midnight Navy", swatch: "bg-sky-950", accent: "bg-sky-300" },
    ],
    collections: ["featured", "best-sellers", "gaming-workspace", "gaming", "trending"],
    tagline: "Hot-swappable wireless keyboard tuned for gaming and focused desk work.",
    description:
      "Aether Mechanical 75 blends premium acoustics with low-latency connectivity. It ships with gasket mounting, tri-mode wireless, shine-through keycaps, and a refined layout that fits cleanly into premium setups.",
    highlights: ["Hot-swappable switches", "Tri-mode wireless", "South-facing RGB"],
    specs: {
      Layout: "75% ANSI",
      Connectivity: "2.4GHz, Bluetooth, USB-C",
      Battery: "5000mAh",
      Mount: "Gasket mount",
      Switches: "Pre-lubed linear switches",
    },
    advisory: "Switch puller and extra caps are included in the box for quick customization.",
    delivery: "Limited warehouse stock",
    reviewsList: [],
  },
  {
    id: 4,
    name: "HaloView 4K Desk Light",
    category: "Smart Home Products",
    price: 129,
    compareAtPrice: 149,
    rating: 0,
    reviews: 0,
    badge: "New",
    stock: 14,
    serialNumber: "MC-HOM-4016",
    illustration: "light",
    palette: {
      panel: "from-emerald-500/16 via-slate-950 to-slate-900",
      glow: "bg-emerald-400/20",
      accent: "text-emerald-300",
      border: "border-emerald-400/20",
    },
    variants: [
      { id: "sage", name: "Sage Alloy", swatch: "bg-emerald-600", accent: "bg-emerald-300" },
      { id: "pearl", name: "Pearl White", swatch: "bg-zinc-100", accent: "bg-lime-200" },
    ],
    collections: ["new-arrivals", "smart-home", "lifestyle-tech", "trending"],
    tagline: "Bias lighting and task illumination with app-controlled scenes.",
    description:
      "HaloView brightens desk setups, monitor walls, and nightstands with a slim 4K-safe light bar. It pairs with voice assistants and custom schedules so your space feels polished without effort.",
    highlights: ["Adaptive color temperature", "Ambient sync scenes", "Touch and app controls"],
    specs: {
      Brightness: "900 lumens",
      Temperature: "2700K - 6500K",
      Control: "App, touch, voice assistants",
      Mount: "Weighted magnetic base",
      Power: "USB-C PD",
    },
    advisory: "Mount above or behind a display for the most balanced bias-light effect.",
    delivery: "Ships in 2 business days",
    reviewsList: [],
  },
  {
    id: 5,
    name: "Strata Creator Dock",
    category: "Creator & Streaming Accessories",
    price: 239,
    compareAtPrice: 279,
    rating: 0,
    reviews: 0,
    badge: "Premium",
    stock: 7,
    serialNumber: "MC-CRT-5188",
    illustration: "dock",
    palette: {
      panel: "from-rose-400/16 via-slate-950 to-slate-900",
      glow: "bg-rose-400/20",
      accent: "text-rose-300",
      border: "border-rose-400/20",
    },
    variants: [
      { id: "graphite", name: "Graphite", swatch: "bg-zinc-800", accent: "bg-rose-300" },
      { id: "silver", name: "Studio Silver", swatch: "bg-zinc-300", accent: "bg-pink-200" },
    ],
    collections: ["featured", "creator", "gaming-workspace", "best-sellers"],
    tagline: "An all-in-one connectivity hub for creators running cameras, drives, and displays.",
    description:
      "Strata Creator Dock keeps demanding setups organized with high-speed ports, dual 4K output, UHS-II card access, and front-facing quick-connect inputs for cameras and audio interfaces.",
    highlights: ["Dual 4K display support", "UHS-II SD + microSD", "2.5GbE networking"],
    specs: {
      Upstream: "Thunderbolt 4 / USB4",
      Displays: "2 x 4K @ 60Hz",
      Storage: "10Gbps USB-C ports",
      Networking: "2.5 Gigabit Ethernet",
      Audio: "3.5mm combo jack",
    },
    advisory: "Use an external power source when connecting bus-powered drives and capture devices together.",
    delivery: "Premium support included",
    reviewsList: [],
  },
  {
    id: 6,
    name: "PulsePad RGB Mouse Mat",
    category: "Gaming Accessories",
    price: 59,
    compareAtPrice: 79,
    rating: 0,
    reviews: 0,
    badge: "Flash Deal",
    stock: 21,
    serialNumber: "MC-GAM-1180",
    illustration: "mousepad",
    palette: {
      panel: "from-fuchsia-500/16 via-slate-950 to-slate-900",
      glow: "bg-fuchsia-400/20",
      accent: "text-fuchsia-300",
      border: "border-fuchsia-400/20",
    },
    variants: [
      { id: "neon", name: "Neon Edge", swatch: "bg-fuchsia-500", accent: "bg-fuchsia-300" },
      { id: "ice", name: "Ice Blue", swatch: "bg-sky-400", accent: "bg-cyan-300" },
    ],
    collections: ["flash-deals", "gaming", "trending"],
    tagline: "A spacious low-friction desk mat with perimeter glow and USB-C power.",
    description:
      "PulsePad delivers smooth tracking, anti-fray edges, and synchronized lighting presets that tie into gaming rooms without overwhelming the setup. The surface feels fast for shooters and controlled for creative work.",
    highlights: ["800 x 300mm surface", "Water-resistant coating", "Addressable RGB edge"],
    specs: {
      Surface: "Speed-control hybrid weave",
      Size: "800 x 300mm",
      Lighting: "12 RGB presets",
      Cable: "Detachable USB-C",
      Base: "Textured anti-slip rubber",
    },
    advisory: "Keep the USB-C connector seated firmly to avoid intermittent lighting disconnects.",
    delivery: "Flash deal shipping today",
    reviewsList: [],
  },
  {
    id: 7,
    name: "Summit Fold Laptop Stand",
    category: "Laptops & Workspace Setup",
    price: 74,
    compareAtPrice: 94,
    rating: 0,
    reviews: 0,
    badge: "Workspace Pick",
    stock: 18,
    serialNumber: "MC-WRK-2476",
    illustration: "stand",
    palette: {
      panel: "from-slate-400/16 via-slate-950 to-slate-900",
      glow: "bg-slate-300/20",
      accent: "text-slate-200",
      border: "border-white/10",
    },
    variants: [
      { id: "silver", name: "Brushed Silver", swatch: "bg-zinc-300", accent: "bg-zinc-100" },
      { id: "black", name: "Midnight Black", swatch: "bg-zinc-800", accent: "bg-slate-300" },
    ],
    collections: ["gaming-workspace", "workspace", "best-sellers"],
    tagline: "A fold-flat laptop riser that adds ergonomics without adding bulk.",
    description:
      "Summit Fold raises displays to a healthier viewing angle and packs away quickly when you move between desk, studio, and campus. Silicone contact points keep premium laptops stable and scratch free.",
    highlights: ["Supports laptops up to 17 inches", "Folds flat for travel", "Aerospace aluminum frame"],
    specs: {
      Material: "Anodized aluminum",
      Weight: "480g",
      Angle: "6 adjustable positions",
      Compatibility: "Up to 17-inch laptops",
      Extras: "Silicone protection pads",
    },
    advisory: "Pair with an external keyboard for the best ergonomic result during long sessions.",
    delivery: "Back in stock",
    reviewsList: [],
  },
  {
    id: 8,
    name: "Orbit Smart Tracker Card",
    category: "Smart Gadgets",
    price: 39,
    compareAtPrice: 49,
    rating: 0,
    reviews: 0,
    badge: "Everyday Essential",
    stock: 34,
    serialNumber: "MC-SGD-0983",
    illustration: "tracker",
    palette: {
      panel: "from-sky-400/16 via-slate-950 to-slate-900",
      glow: "bg-sky-300/20",
      accent: "text-sky-300",
      border: "border-sky-400/20",
    },
    variants: [
      { id: "black", name: "Black Carbon", swatch: "bg-zinc-900", accent: "bg-sky-300" },
      { id: "white", name: "Pearl White", swatch: "bg-zinc-100", accent: "bg-cyan-200" },
    ],
    collections: ["smart-gadgets", "new-arrivals", "mobile", "featured"],
    tagline: "Wallet-friendly tracker card with global find-network support.",
    description:
      "Orbit slips into wallets, passports, and travel sleeves while giving you reliable location pings and separation alerts. The rechargeable battery lasts months and the finish stays clean even with daily use.",
    highlights: ["Rechargeable battery", "Find-network ready", "Ultra-thin card design"],
    specs: {
      Thickness: "2.2mm",
      Battery: "5 months per charge",
      Charging: "Magnetic cable",
      Alerts: "Separation + ping",
      Range: "Global network support",
    },
    advisory: "Best stored in the outer card layer of a wallet for strongest signal performance.",
    delivery: "Ships same day",
    reviewsList: [],
  },
  {
    id: 9,
    name: "FrameFlow LUT Bundle",
    category: "Trending Digital Products",
    price: 29,
    compareAtPrice: 39,
    rating: 0,
    reviews: 0,
    badge: "Digital Download",
    stock: 999,
    serialNumber: "MC-DIG-5520",
    illustration: "digital",
    palette: {
      panel: "from-indigo-500/18 via-slate-950 to-slate-900",
      glow: "bg-indigo-400/20",
      accent: "text-indigo-300",
      border: "border-indigo-400/20",
    },
    variants: [
      { id: "cinema", name: "Cinema Pack", swatch: "bg-indigo-500", accent: "bg-indigo-300" },
      { id: "social", name: "Social Pack", swatch: "bg-pink-500", accent: "bg-pink-300" },
    ],
    collections: ["digital", "new-arrivals", "creator", "trending"],
    tagline: "Cinematic color presets for creators shipping short-form and long-form video faster.",
    description:
      "FrameFlow includes flexible LUTs designed for moody desk setups, gaming highlights, product reels, and podcast footage. Install in minutes and keep your visual identity consistent across platforms.",
    highlights: ["Works with Premiere, Final Cut, Resolve", "Optimized for LED-lit setups", "Instant download"],
    specs: {
      Format: ".cube LUT pack",
      Includes: "18 LUTs + install guide",
      Delivery: "Instant digital download",
      License: "Single creator commercial use",
      Support: "Setup guide included",
    },
    advisory: "Apply on properly exposed footage and dial intensity down for skin tones when needed.",
    delivery: "Available instantly after checkout",
    reviewsList: [],
  },
  {
    id: 10,
    name: "Luma Bottle Pro",
    category: "Lifestyle Tech Products",
    price: 69,
    compareAtPrice: 89,
    rating: 0,
    reviews: 0,
    badge: "New",
    stock: 20,
    serialNumber: "MC-LIF-3022",
    illustration: "lifestyle",
    palette: {
      panel: "from-teal-400/16 via-slate-950 to-slate-900",
      glow: "bg-teal-300/20",
      accent: "text-teal-300",
      border: "border-teal-400/20",
    },
    variants: [
      { id: "mint", name: "Mint Steel", swatch: "bg-teal-400", accent: "bg-teal-200" },
      { id: "graphite", name: "Graphite", swatch: "bg-zinc-800", accent: "bg-teal-300" },
    ],
    collections: ["lifestyle-tech", "new-arrivals", "featured"],
    tagline: "A self-cleaning smart bottle built for commuters, students, and creators on the move.",
    description:
      "Luma Bottle Pro keeps drinks cold, tracks hydration reminders, and uses UV-C cleaning cycles to make everyday carry feel smarter. The brushed steel finish looks premium instead of gimmicky.",
    highlights: ["UV-C self-clean cycle", "Hydration reminders", "24-hour cold retention"],
    specs: {
      Capacity: "620ml",
      Material: "Vacuum insulated stainless steel",
      Battery: "14-day charge",
      Cleaning: "UV-C interior cycle",
      Extras: "LED status ring",
    },
    advisory: "Run a cleaning cycle with the lid closed and bottle empty for best results.",
    delivery: "Ships tomorrow",
    reviewsList: [],
  },
  {
    id: 11,
    name: "Arc Mini Projector",
    category: "Everyday Tech Essentials",
    price: 199,
    compareAtPrice: 249,
    rating: 0,
    reviews: 0,
    badge: "Weekend Pick",
    stock: 13,
    serialNumber: "MC-ESS-6733",
    illustration: "projector",
    palette: {
      panel: "from-orange-400/16 via-slate-950 to-slate-900",
      glow: "bg-orange-300/20",
      accent: "text-orange-300",
      border: "border-orange-300/20",
    },
    variants: [
      { id: "sand", name: "Sandstone", swatch: "bg-stone-300", accent: "bg-orange-200" },
      { id: "graphite", name: "Graphite", swatch: "bg-zinc-800", accent: "bg-orange-300" },
    ],
    collections: ["featured", "smart-gadgets", "lifestyle-tech"],
    tagline: "Pocket-friendly projector for dorm rooms, lounge spaces, and quick presentations.",
    description:
      "Arc Mini Projector brings big-screen energy to small rooms with auto-keystone, built-in streaming, and a surprisingly rich speaker tuned for casual watching. It is perfect for flexible modern living.",
    highlights: ["Auto focus and keystone", "Built-in streaming apps", "Compact carry design"],
    specs: {
      Resolution: "1080p native",
      Brightness: "450 ANSI lumens",
      Audio: "Dual stereo speakers",
      Wireless: "Wi-Fi 6 + Bluetooth",
      Projection: "40 to 120 inches",
    },
    advisory: "Use in dimmer rooms for the best contrast and color depth.",
    delivery: "Ships in 48 hours",
    reviewsList: [],
  },
  {
    id: 12,
    name: "Nova Webcam Studio",
    category: "Creator & Streaming Accessories",
    price: 119,
    compareAtPrice: 149,
    rating: 0,
    reviews: 0,
    badge: "Creator Favorite",
    stock: 15,
    serialNumber: "MC-CRT-8841",
    illustration: "camera",
    palette: {
      panel: "from-red-400/16 via-slate-950 to-slate-900",
      glow: "bg-red-300/20",
      accent: "text-red-300",
      border: "border-red-300/20",
    },
    variants: [
      { id: "black", name: "Studio Black", swatch: "bg-zinc-900", accent: "bg-red-300" },
      { id: "white", name: "Porcelain White", swatch: "bg-zinc-100", accent: "bg-rose-200" },
    ],
    collections: ["creator", "best-sellers", "new-arrivals", "gaming-workspace"],
    tagline: "A sharp 4K webcam with clean low-light tuning and instant framing.",
    description:
      "Nova Webcam Studio upgrades meetings, streaming, and recorded content with crisp optics, dual microphones, and polished framing that feels professional right out of the box.",
    highlights: ["4K sensor", "Auto framing", "Dual noise-reduced microphones"],
    specs: {
      Resolution: "4K30 / 1080p60",
      FieldOfView: "90 degrees",
      Mount: "Monitor clip + tripod thread",
      Audio: "Dual beamforming mics",
      Privacy: "Magnetic privacy cover",
    },
    advisory: "Mount slightly above eye line and keep a soft key light in front for the best image.",
    delivery: "Creator support included",
    reviewsList: [],
  },
  {
    id: 13,
    name: "EchoStream Fold",
    category: "Wireless Headphones & Audio",
    price: 199,
    compareAtPrice: 239,
    rating: 0,
    reviews: 0,
    badge: "Portable",
    stock: 18,
    serialNumber: "MC-AUD-2113",
    illustration: "headphones",
    palette: {
      panel: "from-sky-500/18 via-slate-950 to-slate-900",
      glow: "bg-sky-400/20",
      accent: "text-sky-300",
      border: "border-sky-400/20",
    },
    variants: [
      { id: "midnight", name: "Midnight Blue", swatch: "bg-slate-900", accent: "bg-sky-300" },
      { id: "opal", name: "Opal White", swatch: "bg-slate-100", accent: "bg-cyan-200" },
    ],
    collections: ["featured", "audio", "mobile", "new-arrivals"],
    tagline: "Foldable wireless headphones for travel, video calls, and music on the go.",
    description:
      "EchoStream Fold brings studio tuning to a travel-ready wireless headset with ANC, a fold-flat design, and intuitive touch controls.",
    highlights: ["40-hour battery", "Active noise cancellation", "Fold-flat travel design"],
    specs: {
      Drivers: "40mm dynamic drivers",
      Connectivity: "Bluetooth 5.3",
      Battery: "40 hours",
      Charging: "USB-C fast charge",
      Controls: "Touch gesture control",
    },
    advisory: "Charge before long flights and store in the included soft carry pouch.",
    delivery: "Ships in 24 hours",
    reviewsList: [],
  },
  {
    id: 14,
    name: "PulseBass Neckband",
    category: "Wireless Headphones & Audio",
    price: 89,
    compareAtPrice: 119,
    rating: 0,
    reviews: 0,
    badge: "Active",
    stock: 27,
    serialNumber: "MC-AUD-1420",
    illustration: "earbuds",
    palette: {
      panel: "from-fuchsia-500/18 via-slate-950 to-slate-900",
      glow: "bg-fuchsia-400/20",
      accent: "text-fuchsia-300",
      border: "border-fuchsia-400/20",
    },
    variants: [
      { id: "storm", name: "Storm Gray", swatch: "bg-zinc-700", accent: "bg-fuchsia-300" },
      { id: "mint", name: "Mint Green", swatch: "bg-emerald-400", accent: "bg-sky-200" },
    ],
    collections: ["audio", "mobile", "best-sellers"],
    tagline: "Sweat-resistant neckband earbuds built for workouts and calls.",
    description:
      "PulseBass delivers rich bass, secure fit, and voice optimization for on-the-go users who need comfort and confidence during activities.",
    highlights: ["Secure sport fit", "Voice clarity mode", "Magnetic earbud pairing"],
    specs: {
      Drivers: "10mm dynamic",
      Connectivity: "Bluetooth 5.2",
      Battery: "18 hours",
      WaterResistance: "IPX6",
      Extras: "Magnetic snap dwell",
    },
    advisory: "Keep the magnetized earbuds together when not in use to preserve battery life.",
    delivery: "Ships today",
    reviewsList: [],
  },
  {
    id: 15,
    name: "AeroSphere Studio Monitors",
    category: "Wireless Headphones & Audio",
    price: 329,
    compareAtPrice: 369,
    rating: 0,
    reviews: 0,
    badge: "Studio",
    stock: 12,
    serialNumber: "MC-AUD-7315",
    illustration: "speakers",
    palette: {
      panel: "from-cyan-500/18 via-slate-950 to-slate-900",
      glow: "bg-cyan-300/20",
      accent: "text-cyan-200",
      border: "border-cyan-300/20",
    },
    variants: [
      { id: "black", name: "Black Quartz", swatch: "bg-zinc-900", accent: "bg-cyan-200" },
      { id: "white", name: "White Pearl", swatch: "bg-zinc-100", accent: "bg-sky-200" },
    ],
    collections: ["featured", "audio", "creator", "new-arrivals"],
    tagline: "Nearfield monitors for creators who want accurate sound and a premium desktop presence.",
    description:
      "AeroSphere gives you clear mix translation for video editing, podcasting, and music playback in a compact, refined package.",
    highlights: ["Balanced reference sound", "Dual-driver design", "Room calibration support"],
    specs: {
      Drivers: "5-inch woofer + 1-inch tweeter",
      Power: "120W peak",
      Connectivity: "USB-C + analog",
      Calibration: "Built-in room tuning",
      Finish: "Matte charcoal or alpine",
    },
    advisory: "Place them at ear level and keep the listening triangle tight for best accuracy.",
    delivery: "Ships in 2 business days",
    reviewsList: [],
  },
  {
    id: 16,
    name: "ChargeLoop MagPad",
    category: "Mobile Accessories",
    price: 64,
    compareAtPrice: 84,
    rating: 0,
    reviews: 0,
    badge: "MagSafe",
    stock: 31,
    serialNumber: "MC-MOB-6431",
    illustration: "charger",
    palette: {
      panel: "from-amber-400/16 via-slate-950 to-slate-900",
      glow: "bg-amber-300/20",
      accent: "text-amber-300",
      border: "border-amber-300/20",
    },
    variants: [
      { id: "black", name: "Obsidian", swatch: "bg-zinc-900", accent: "bg-amber-300" },
      { id: "cream", name: "Sahara Cream", swatch: "bg-amber-100", accent: "bg-amber-200" },
    ],
    collections: ["mobile", "best-sellers", "new-arrivals"],
    tagline: "A magnetic fast charger for iPhone, AirPods, and wireless earbuds in one sleek pad.",
    description:
      "ChargeLoop delivers a clean desk experience with fast magnetic alignment, Qi compatibility, and a compact silhouette that fits anywhere.",
    highlights: ["15W magnetic charging", "Dual-device support", "Anti-slip finish"],
    specs: {
      Output: "15W MagSafe + 7.5W Qi",
      Ports: "USB-C input",
      Material: "Textured matte polymer",
      Included: "USB-C cable",
      Compatibility: "MagSafe and Qi devices",
    },
    advisory: "Pair with a 20W USB-C adapter for the fastest MagSafe speed.",
    delivery: "Ships same day",
    reviewsList: [],
  },
  {
    id: 17,
    name: "GripFlex Phone Mount",
    category: "Mobile Accessories",
    price: 39,
    compareAtPrice: 49,
    rating: 0,
    reviews: 0,
    badge: "Mount",
    stock: 24,
    serialNumber: "MC-MOB-1717",
    illustration: "mount",
    palette: {
      panel: "from-violet-500/18 via-slate-950 to-slate-900",
      glow: "bg-violet-400/20",
      accent: "text-violet-300",
      border: "border-violet-400/20",
    },
    variants: [
      { id: "black", name: "Night Black", swatch: "bg-zinc-900", accent: "bg-violet-300" },
      { id: "sand", name: "Sandstone", swatch: "bg-stone-300", accent: "bg-amber-200" },
    ],
    collections: ["mobile", "workspace", "smart-gadgets"],
    tagline: "A flexible magnetic mount for phones, tablets, and accessory hubs.",
    description:
      "GripFlex keeps screens visible at desk, bedside, or in the kitchen with an adjustable arm and strong magnetic hold.",
    highlights: ["360° swivel", "Magnetically compatible", "Low-profile base"],
    specs: {
      Height: "Up to 30cm adjustable",
      Compatibility: "MagSafe and metal plates",
      Mount: "Weighted desk base",
      Finish: "Soft-touch coating",
      Extras: "Fold-flat storage",
    },
    advisory: "Use on flat, stable surfaces for the best hold.",
    delivery: "Ships today",
    reviewsList: [],
  },
  {
    id: 18,
    name: "SilkShield Screen Kit",
    category: "Mobile Accessories",
    price: 24,
    compareAtPrice: 34,
    rating: 0,
    reviews: 0,
    badge: "Essential",
    stock: 44,
    serialNumber: "MC-MOB-1824",
    illustration: "screen",
    palette: {
      panel: "from-slate-400/16 via-slate-950 to-slate-900",
      glow: "bg-slate-300/20",
      accent: "text-slate-200",
      border: "border-white/10",
    },
    variants: [
      { id: "clear", name: "Clear Shield", swatch: "bg-slate-100", accent: "bg-slate-200" },
      { id: "privacy", name: "Privacy Guard", swatch: "bg-zinc-900", accent: "bg-zinc-300" },
    ],
    collections: ["mobile", "lifestyle-tech", "everyday-tech"],
    tagline: "A premium screen protector kit with easy alignment and smudge-resistant coating.",
    description:
      "SilkShield keeps devices looking new with reinforced glass, precise fit, and a fast-install tray for every phone size.",
    highlights: ["9H hardness", "Anti-fingerprint", "Easy installation"],
    specs: {
      Material: "Tempered glass",
      Compatibility: "Most modern phones",
      Included: "Alignment tray + wipes",
      Coverage: "Full edge-to-edge",
      Warranty: "1-year replacement",
    },
    advisory: "Clean surfaces thoroughly before installing to avoid bubbles.",
    delivery: "Ships in 24 hours",
    reviewsList: [],
  },
  {
    id: 19,
    name: "BlazeFire Elite Mouse",
    category: "Gaming Accessories",
    price: 119,
    compareAtPrice: 149,
    rating: 0,
    reviews: 0,
    badge: "Pro",
    stock: 22,
    serialNumber: "MC-GAM-1911",
    illustration: "mouse",
    palette: {
      panel: "from-red-500/18 via-slate-950 to-slate-900",
      glow: "bg-red-300/20",
      accent: "text-red-300",
      border: "border-red-300/20",
    },
    variants: [
      { id: "black", name: "Phantom Black", swatch: "bg-zinc-900", accent: "bg-red-300" },
      { id: "silver", name: "Silver Edge", swatch: "bg-slate-300", accent: "bg-red-200" },
    ],
    collections: ["gaming", "best-sellers", "gaming-workspace"],
    tagline: "A lightweight wired gaming mouse built for fast action and precision.",
    description:
      "BlazeFire Elite offers a durable shell, low-friction feet, and customizable buttons for both competitive matches and creative work.",
    highlights: ["66g lightweight design", "11 programmable buttons", "PTFE skates"],
    specs: {
      Sensor: "30K DPI optical",
      Switches: "Durable mechanical",
      Connectivity: "Wired USB-C",
      Weight: "66 grams",
      Cable: "2m paracord",
    },
    advisory: "Use on a flat desk mat for the best tracking consistency.",
    delivery: "Ships today",
    reviewsList: [],
  },
  {
    id: 20,
    name: "Phantom Chill Pad",
    category: "Gaming Accessories",
    price: 49,
    compareAtPrice: 69,
    rating: 0,
    reviews: 0,
    badge: "Cooler",
    stock: 28,
    serialNumber: "MC-GAM-2020",
    illustration: "pad",
    palette: {
      panel: "from-indigo-500/18 via-slate-950 to-slate-900",
      glow: "bg-indigo-400/20",
      accent: "text-indigo-300",
      border: "border-indigo-400/20",
    },
    variants: [
      { id: "black", name: "Black Chill", swatch: "bg-zinc-900", accent: "bg-indigo-300" },
      { id: "blue", name: "Glacier Blue", swatch: "bg-sky-400", accent: "bg-indigo-200" },
    ],
    collections: ["gaming", "workspace", "trending"],
    tagline: "A gaming mouse pad with textured control and premium performance.",
    description:
      "Phantom Chill lets you track every move precisely while giving your desk a muted, modern look with stitched edges and non-slip backing.",
    highlights: ["Speed-control surface", "Stitched edges", "Rubber anti-slip base"],
    specs: {
      Size: "450 x 400mm",
      Thickness: "4mm",
      Surface: "Textured woven fabric",
      Base: "Non-slip rubber",
      Extras: "Water-resistant finish",
    },
    advisory: "Keep the surface clean with a damp cloth for consistent tracking.",
    delivery: "Ships tomorrow",
    reviewsList: [],
  },
  {
    id: 21,
    name: "NovaStrike Gamepad",
    category: "Gaming Accessories",
    price: 99,
    compareAtPrice: 129,
    rating: 0,
    reviews: 0,
    badge: "Comfort",
    stock: 15,
    serialNumber: "MC-GAM-2114",
    illustration: "gamepad",
    palette: {
      panel: "from-slate-400/16 via-slate-950 to-slate-900",
      glow: "bg-slate-300/20",
      accent: "text-slate-200",
      border: "border-white/10",
    },
    variants: [
      { id: "charcoal", name: "Charcoal", swatch: "bg-zinc-800", accent: "bg-slate-200" },
      { id: "ember", name: "Ember Red", swatch: "bg-red-600", accent: "bg-rose-200" },
    ],
    collections: ["gaming", "featured", "trending"],
    tagline: "A versatile gamepad for console-style play, cloud streaming, and PC titles.",
    description:
      "NovaStrike gives a premium grip feel, swappable stick modules, and low-latency wireless for modern gaming sessions.",
    highlights: ["Modular thumbsticks", "Low-latency wireless", "Comfort grip"],
    specs: {
      Connectivity: "Bluetooth + wired USB-C",
      Battery: "40 hours",
      Buttons: "Anti-ghosting",
      Compatibility: "PC, mobile, console",
      Extras: "Swappable thumb caps",
    },
    advisory: "Pair directly with supported devices and keep firmware updated for new features.",
    delivery: "Ships in 24 hours",
    reviewsList: [],
  },
  {
    id: 22,
    name: "AuraSense Smart Thermostat",
    category: "Smart Home Products",
    price: 189,
    compareAtPrice: 229,
    rating: 0,
    reviews: 0,
    badge: "Energy",
    stock: 14,
    serialNumber: "MC-HOM-2222",
    illustration: "thermostat",
    palette: {
      panel: "from-emerald-500/16 via-slate-950 to-slate-900",
      glow: "bg-emerald-400/20",
      accent: "text-emerald-300",
      border: "border-emerald-400/20",
    },
    variants: [
      { id: "white", name: "Soft White", swatch: "bg-zinc-100", accent: "bg-emerald-300" },
      { id: "black", name: "Midnight Black", swatch: "bg-zinc-900", accent: "bg-emerald-300" },
    ],
    collections: ["smart-home", "lifestyle-tech", "new-arrivals"],
    tagline: "A learning thermostat that keeps rooms comfortable while trimming energy waste.",
    description:
      "AuraSense adapts to your schedule, supports voice controls, and uses smart routines for efficient climate management.",
    highlights: ["Adaptive temperature learning", "App + voice control", "Energy reports"],
    specs: {
      Compatibility: "Most HVAC systems",
      Control: "App, voice, touchscreen",
      Display: "Color LCD",
      Sensors: "Motion + humidity",
      Power: "Battery or C-wire",
    },
    advisory: "Work with a qualified installer if you are unsure about your HVAC wiring.",
    delivery: "Ships in 2 business days",
    reviewsList: [],
  },
  {
    id: 23,
    name: "SleepPod Sound Column",
    category: "Smart Home Products",
    price: 129,
    compareAtPrice: 159,
    rating: 0,
    reviews: 0,
    badge: "Relax",
    stock: 19,
    serialNumber: "MC-HOM-2323",
    illustration: "speaker",
    palette: {
      panel: "from-indigo-500/18 via-slate-950 to-slate-900",
      glow: "bg-indigo-400/20",
      accent: "text-indigo-300",
      border: "border-indigo-400/20",
    },
    variants: [
      { id: "charcoal", name: "Charcoal", swatch: "bg-zinc-800", accent: "bg-indigo-300" },
      { id: "stone", name: "Stone", swatch: "bg-slate-300", accent: "bg-slate-200" },
    ],
    collections: ["smart-home", "lifestyle-tech", "new-arrivals"],
    tagline: "A compact sound column designed to support sleep routines and ambient home scenes.",
    description:
      "SleepPod blends soft audio, light cues, and sleep-focused programs for resting spaces and evening routines.",
    highlights: ["Sleep sounds + meditation", "Ambient lighting", "App controls"],
    specs: {
      Audio: "Stereo sound",
      Lighting: "Ambient LED",
      Connectivity: "Wi-Fi + Bluetooth",
      Controls: "App + touch",
      Compatibility: "Smart home platforms",
    },
    advisory: "Place on a nightstand and keep firmware updated for the latest sleep sound library.",
    delivery: "Ships tomorrow",
    reviewsList: [],
  },
  {
    id: 24,
    name: "PulseAir Wireless Diffuser",
    category: "Smart Home Products",
    price: 79,
    compareAtPrice: 99,
    rating: 0,
    reviews: 0,
    badge: "Wellness",
    stock: 25,
    serialNumber: "MC-HOM-2424",
    illustration: "diffuser",
    palette: {
      panel: "from-teal-400/16 via-slate-950 to-slate-900",
      glow: "bg-teal-300/20",
      accent: "text-teal-300",
      border: "border-teal-400/20",
    },
    variants: [
      { id: "oasis", name: "Oasis", swatch: "bg-teal-400", accent: "bg-teal-200" },
      { id: "cinder", name: "Cinder", swatch: "bg-zinc-800", accent: "bg-slate-400" },
    ],
    collections: ["smart-home", "lifestyle-tech", "featured"],
    tagline: "A rechargeable diffuser with quiet mist and app-timed scent routines.",
    description:
      "PulseAir adds calming aroma to bedrooms and living areas with a minimal design and easy refill system.",
    highlights: ["Quiet ultrasonic mist", "Wireless charging", "Timer controls"],
    specs: {
      Capacity: "200ml",
      Runtime: "Up to 12 hours",
      Power: "USB-C rechargeable",
      Control: "App + buttons",
      Extras: "Essential oil tray",
    },
    advisory: "Use with distilled water and compatible essential oils for best performance.",
    delivery: "Ships same day",
    reviewsList: [],
  },
  {
    id: 25,
    name: "Lyra Audio Interface",
    category: "Creator & Streaming Accessories",
    price: 219,
    compareAtPrice: 259,
    rating: 0,
    reviews: 0,
    badge: "Studio",
    stock: 13,
    serialNumber: "MC-CRT-2525",
    illustration: "audio-interface",
    palette: {
      panel: "from-rose-400/16 via-slate-950 to-slate-900",
      glow: "bg-rose-400/20",
      accent: "text-rose-300",
      border: "border-rose-400/20",
    },
    variants: [
      { id: "black", name: "Black Studio", swatch: "bg-zinc-900", accent: "bg-rose-300" },
      { id: "white", name: "White Studio", swatch: "bg-zinc-100", accent: "bg-pink-200" },
    ],
    collections: ["creator", "best-sellers", "studio"],
    tagline: "A compact interface for podcasting, streaming, and creative voice work.",
    description:
      "Lyra gives you two premium preamps, loopback mixing, and simple monitoring in a polished desktop design.",
    highlights: ["2x XLR/line inputs", "Loopback mix", "USB-C connectivity"],
    specs: {
      Inputs: "2 x XLR/TRS combo",
      Outputs: "2 balanced monitors",
      BitDepth: "24-bit/192kHz",
      Controls: "Gain + monitor mix",
      Compatibility: "Mac, Windows",
    },
    advisory: "Use with studio-grade microphones for the best streaming and recording quality.",
    delivery: "Ships in 48 hours",
    reviewsList: [],
  },
  {
    id: 26,
    name: "Beam Light Panel",
    category: "Creator & Streaming Accessories",
    price: 149,
    compareAtPrice: 179,
    rating: 0,
    reviews: 0,
    badge: "Lighting",
    stock: 16,
    serialNumber: "MC-CRT-2626",
    illustration: "light-panel",
    palette: {
      panel: "from-cyan-500/18 via-slate-950 to-slate-900",
      glow: "bg-cyan-300/20",
      accent: "text-cyan-200",
      border: "border-cyan-300/20",
    },
    variants: [
      { id: "white", name: "Soft White", swatch: "bg-slate-100", accent: "bg-cyan-300" },
      { id: "black", name: "Studio Black", swatch: "bg-zinc-900", accent: "bg-slate-100" },
    ],
    collections: ["creator", "streaming", "workspace"],
    tagline: "A color-accurate panel for stream lighting, portraits, and content creation.",
    description:
      "Beam blends adjustable color, brightness, and diffusion with a rugged, desk-mounted design.",
    highlights: ["RGB + white balance", "App presets", "Low-noise power"],
    specs: {
      Output: "1200 lumens",
      Color: "2700K - 6500K + RGB",
      Mount: "Desk clamp",
      Control: "App + onboard dial",
      Extras: "Diffuser panel",
    },
    advisory: "Position the panel slightly above eye level for the most flattering look.",
    delivery: "Ships today",
    reviewsList: [],
  },
  {
    id: 27,
    name: "StudioMic Live",
    category: "Creator & Streaming Accessories",
    price: 159,
    compareAtPrice: 189,
    rating: 0,
    reviews: 0,
    badge: "Broadcast",
    stock: 14,
    serialNumber: "MC-CRT-2727",
    illustration: "microphone",
    palette: {
      panel: "from-slate-400/16 via-slate-950 to-slate-900",
      glow: "bg-white/20",
      accent: "text-slate-200",
      border: "border-white/10",
    },
    variants: [
      { id: "black", name: "Black Beam", swatch: "bg-zinc-900", accent: "bg-slate-200" },
      { id: "silver", name: "Silver Beam", swatch: "bg-slate-300", accent: "bg-white/80" },
    ],
    collections: ["creator", "streaming", "best-sellers"],
    tagline: "A broadcast microphone made for crystal-clear voice and podcast-ready sound.",
    description:
      "StudioMic Live includes a cardioid capsule, intuitive controls, and built-in headphone monitoring for polished streams.",
    highlights: ["Cardioid pickup", "Headphone output", "Gain and mute controls"],
    specs: {
      Pattern: "Cardioid",
      Connectivity: "USB-C",
      BitDepth: "24-bit/96kHz",
      Headphone: "3.5mm jack",
      Mount: "Desk stand included",
    },
    advisory: "Place the mic off-axis from noisy keyboards to reduce unwanted sound.",
    delivery: "Ships tomorrow",
    reviewsList: [],
  },
  {
    id: 28,
    name: "NovaDesk Monitor Arm",
    category: "Laptops & Workspace Setup",
    price: 129,
    compareAtPrice: 159,
    rating: 0,
    reviews: 0,
    badge: "Ergonomic",
    stock: 21,
    serialNumber: "MC-WRK-2828",
    illustration: "monitor-arm",
    palette: {
      panel: "from-slate-400/16 via-slate-950 to-slate-900",
      glow: "bg-slate-300/20",
      accent: "text-slate-200",
      border: "border-white/10",
    },
    variants: [
      { id: "black", name: "Black Alloy", swatch: "bg-zinc-900", accent: "bg-slate-200" },
      { id: "silver", name: "Silver Alloy", swatch: "bg-slate-300", accent: "bg-white/80" },
    ],
    collections: ["workspace", "gaming-workspace", "best-sellers"],
    tagline: "A gas-spring monitor arm for clean desk setups and flexible screen positioning.",
    description:
      "NovaDesk makes it easy to raise, tilt, and swivel a monitor while freeing up desk space below.",
    highlights: ["Gas-spring lift", "360° rotation", "Desk clamp mount"],
    specs: {
      Weight: "Up to 10kg",
      Reach: "610mm",
      Adjustments: "Height + tilt + swivel",
      Mount: "C-clamp / grommet",
      Finish: "Powder coated aluminum",
    },
    advisory: "Confirm desk thickness and monitor weight before installation.",
    delivery: "Ships in 24 hours",
    reviewsList: [],
  },
  {
    id: 29,
    name: "SwitchPad Wireless Keyboard",
    category: "Laptops & Workspace Setup",
    price: 139,
    compareAtPrice: 169,
    rating: 0,
    reviews: 0,
    badge: "Compact",
    stock: 17,
    serialNumber: "MC-WRK-2929",
    illustration: "keyboard",
    palette: {
      panel: "from-violet-500/18 via-slate-950 to-slate-900",
      glow: "bg-violet-400/20",
      accent: "text-violet-300",
      border: "border-violet-400/20",
    },
    variants: [
      { id: "graphite", name: "Graphite", swatch: "bg-zinc-800", accent: "bg-violet-300" },
      { id: "chalk", name: "Chalk", swatch: "bg-slate-100", accent: "bg-slate-300" },
    ],
    collections: ["workspace", "creator", "gaming-workspace"],
    tagline: "A wireless mechanical keyboard that fits desks and travel cases alike.",
    description:
      "SwitchPad combines hot-swappable switches, tri-mode connectivity, and a compact layout for a refined workspace.",
    highlights: ["75% layout", "Tri-mode wireless", "Hot-swappable switches"],
    specs: {
      Connectivity: "Bluetooth + 2.4GHz + USB-C",
      Battery: "3200mAh",
      Layout: "75% ANSI",
      Switches: "Hot-swappable",
      Extras: "Detachable wrist rest",
    },
    advisory: "Charge before extended wireless sessions and store in a padded sleeve.",
    delivery: "Ships same day",
    reviewsList: [],
  },
  {
    id: 30,
    name: "BreathRest Ergonomic Chair Mat",
    category: "Laptops & Workspace Setup",
    price: 89,
    compareAtPrice: 109,
    rating: 0,
    reviews: 0,
    badge: "Comfort",
    stock: 30,
    serialNumber: "MC-WRK-3030",
    illustration: "mat",
    palette: {
      panel: "from-cyan-500/18 via-slate-950 to-slate-900",
      glow: "bg-cyan-400/20",
      accent: "text-cyan-200",
      border: "border-cyan-300/20",
    },
    variants: [
      { id: "charcoal", name: "Charcoal", swatch: "bg-zinc-900", accent: "bg-cyan-200" },
      { id: "sand", name: "Sand", swatch: "bg-stone-300", accent: "bg-slate-200" },
    ],
    collections: ["workspace", "lifestyle-tech", "everyday-tech"],
    tagline: "A breathable mat that reduces fatigue and protects floors beneath ergonomic chairs.",
    description:
      "BreathRest is built with textured support and a low-profile cushion so rolling and reclining feel smooth.",
    highlights: ["Anti-slip backing", "Water-resistant top", "Low-profile design"],
    specs: {
      Size: "900 x 1200mm",
      Material: "Thermoplastic rubber",
      Thickness: "4mm",
      Compatibility: "Office and gaming chairs",
      Extras: "Easy wipe surface",
    },
    advisory: "Keep the mat flat and clean it with a damp cloth for the best glide.",
    delivery: "Ships today",
    reviewsList: [],
  },
  {
    id: 31,
    name: "PulseBand Health Tracker",
    category: "Smart Gadgets",
    price: 99,
    compareAtPrice: 129,
    rating: 0,
    reviews: 0,
    badge: "Wearable",
    stock: 32,
    serialNumber: "MC-SGD-3131",
    illustration: "wearable",
    palette: {
      panel: "from-sky-400/16 via-slate-950 to-slate-900",
      glow: "bg-sky-300/20",
      accent: "text-sky-300",
      border: "border-sky-400/20",
    },
    variants: [
      { id: "midnight", name: "Midnight", swatch: "bg-zinc-900", accent: "bg-sky-300" },
      { id: "pearl", name: "Pearl", swatch: "bg-slate-100", accent: "bg-cyan-200" },
    ],
    collections: ["smart-gadgets", "lifestyle-tech", "featured"],
    tagline: "A lightweight health tracker for steps, sleep, and daily wellness insights.",
    description:
      "PulseBand tracks activity, heart rate, and sleep patterns while keeping a sleek look for everyday wear.",
    highlights: ["Sleep monitoring", "24/7 heart rate", "Weekly wellness reports"],
    specs: {
      Battery: "7 days",
      Sensors: "Heart rate + accelerometer",
      Connectivity: "Bluetooth",
      Display: "OLED",
      WaterResistance: "5ATM",
    },
    advisory: "Sync to the app nightly to keep your data backed up.",
    delivery: "Ships in 24 hours",
    reviewsList: [],
  },
  {
    id: 32,
    name: "WanderTag GPS Locator",
    category: "Smart Gadgets",
    price: 49,
    compareAtPrice: 69,
    rating: 0,
    reviews: 0,
    badge: "Travel",
    stock: 35,
    serialNumber: "MC-SGD-3232",
    illustration: "tracker",
    palette: {
      panel: "from-sky-400/16 via-slate-950 to-slate-900",
      glow: "bg-sky-300/20",
      accent: "text-sky-300",
      border: "border-sky-400/20",
    },
    variants: [
      { id: "black", name: "Carbon Black", swatch: "bg-zinc-900", accent: "bg-sky-300" },
      { id: "white", name: "Arctic White", swatch: "bg-zinc-100", accent: "bg-cyan-200" },
    ],
    collections: ["smart-gadgets", "travel", "mobile"],
    tagline: "A compact GPS locator for luggage, keys, and on-the-go essentials.",
    description:
      "WanderTag keeps travel gear discoverable with real-time tracking and separation alerts.",
    highlights: ["Global network tracking", "Rechargeable battery", "Compact design"],
    specs: {
      Battery: "30 days",
      Connectivity: "Cell + Bluetooth",
      Range: "Global network",
      Waterproof: "IP67",
      Extras: "Replaceable strap",
    },
    advisory: "Use with the app to set safe zones and view item status instantly.",
    delivery: "Ships same day",
    reviewsList: [],
  },
  {
    id: 33,
    name: "GlowSmart Travel Adapter",
    category: "Smart Gadgets",
    price: 34,
    compareAtPrice: 49,
    rating: 0,
    reviews: 0,
    badge: "Travel",
    stock: 40,
    serialNumber: "MC-SGD-3333",
    illustration: "adapter",
    palette: {
      panel: "from-amber-400/16 via-slate-950 to-slate-900",
      glow: "bg-amber-300/20",
      accent: "text-amber-300",
      border: "border-amber-300/20",
    },
    variants: [
      { id: "gray", name: "Graphite", swatch: "bg-zinc-700", accent: "bg-amber-300" },
      { id: "cream", name: "Sandstone", swatch: "bg-amber-100", accent: "bg-slate-200" },
    ],
    collections: ["smart-gadgets", "mobile", "everyday-tech"],
    tagline: "A universal travel adapter with fast USB-C charging and compact folding plugs.",
    description:
      "GlowSmart helps power devices in over 150 countries with a durable, travel-friendly adapter.",
    highlights: ["Universal plug set", "USB-C Power Delivery", "Compact fold-away"],
    specs: {
      Output: "65W USB-C",
      Compatibility: "Worldwide plug types",
      Safety: "Surge protection",
      Weight: "105g",
      Extras: "Storage pouch",
    },
    advisory: "Use with grounded outlets and check voltage compatibility before connecting devices.",
    delivery: "Ships in 24 hours",
    reviewsList: [],
  },
  {
    id: 34,
    name: "Mito Sleep Mask",
    category: "Lifestyle Tech Products",
    price: 59,
    compareAtPrice: 79,
    rating: 0,
    reviews: 0,
    badge: "Wellness",
    stock: 26,
    serialNumber: "MC-LIF-3434",
    illustration: "mask",
    palette: {
      panel: "from-teal-400/16 via-slate-950 to-slate-900",
      glow: "bg-teal-300/20",
      accent: "text-teal-300",
      border: "border-teal-400/20",
    },
    variants: [
      { id: "midnight", name: "Night Sky", swatch: "bg-zinc-950", accent: "bg-teal-300" },
      { id: "rose", name: "Rosewood", swatch: "bg-rose-500", accent: "bg-pink-200" },
    ],
    collections: ["lifestyle-tech", "wellness", "smart-home"],
    tagline: "A smart sleep mask with calming audio and gentle light support.",
    description:
      "Mito Sleep Mask combines comfort, soundscapes, and guided breathing to help you fall asleep faster.",
    highlights: ["Ambient audio", "Gentle light cues", "Soft memory foam"],
    specs: {
      Battery: "12 hours",
      Connectivity: "Bluetooth",
      Controls: "On-mask buttons",
      Material: "Memory foam + microfiber",
      Extras: "Washable cover",
    },
    advisory: "Use with the included travel pouch for safe storage.",
    delivery: "Ships today",
    reviewsList: [],
  },
  {
    id: 35,
    name: "VibePen Smart Notebook",
    category: "Lifestyle Tech Products",
    price: 49,
    compareAtPrice: 69,
    rating: 0,
    reviews: 0,
    badge: "Analog",
    stock: 28,
    serialNumber: "MC-LIF-3535",
    illustration: "notebook",
    palette: {
      panel: "from-slate-400/16 via-slate-950 to-slate-900",
      glow: "bg-white/20",
      accent: "text-slate-200",
      border: "border-white/10",
    },
    variants: [
      { id: "charcoal", name: "Charcoal", swatch: "bg-zinc-900", accent: "bg-slate-200" },
      { id: "mist", name: "Morning Mist", swatch: "bg-slate-200", accent: "bg-slate-100" },
    ],
    collections: ["lifestyle-tech", "creator", "mobile"],
    tagline: "A reusable smart notebook that digitizes notes and ideas with one swipe.",
    description:
      "VibePen is made for planners, students, and creators who want analog notes backed up digitally.",
    highlights: ["Reusable pages", "App sync", "Stylus included"],
    specs: {
      Pages: "40 reusable sheets",
      Connectivity: "Bluetooth",
      Includes: "Smart pen",
      Compatibility: "iOS + Android",
      Extras: "Cloud backup",
    },
    advisory: "Use the included microfiber cloth to keep pages clean.",
    delivery: "Ships in 24 hours",
    reviewsList: [],
  },
  {
    id: 36,
    name: "ChargePack Solar Wallet",
    category: "Lifestyle Tech Products",
    price: 79,
    compareAtPrice: 99,
    rating: 0,
    reviews: 0,
    badge: "Portable",
    stock: 22,
    serialNumber: "MC-LIF-3636",
    illustration: "wallet",
    palette: {
      panel: "from-amber-400/16 via-slate-950 to-slate-900",
      glow: "bg-amber-300/20",
      accent: "text-amber-300",
      border: "border-amber-300/20",
    },
    variants: [
      { id: "tan", name: "Tan Leather", swatch: "bg-amber-200", accent: "bg-slate-300" },
      { id: "graphite", name: "Graphite", swatch: "bg-zinc-800", accent: "bg-amber-300" },
    ],
    collections: ["lifestyle-tech", "smart-gadgets", "mobile"],
    tagline: "A solar-powered wallet with a compact battery for daily power and secure card storage.",
    description:
      "ChargePack blends everyday carry with solar-friendly juice to keep small devices topped up on the go.",
    highlights: ["Solar charging panel", "Built-in battery", "RFID-safe compartments"],
    specs: {
      Capacity: "5,000mAh",
      Material: "Vegetable-tanned leather",
      Charging: "Solar + USB-C",
      Compatibility: "Phones + earbuds",
      Extras: "RFID protection",
    },
    advisory: "Allow the solar panel to charge in sunlight before travel.",
    delivery: "Ships same day",
    reviewsList: [],
  },
  {
    id: 37,
    name: "StreamFX Overlay Pack",
    category: "Trending Digital Products",
    price: 19,
    compareAtPrice: 29,
    rating: 0,
    reviews: 0,
    badge: "Digital",
    stock: 999,
    serialNumber: "MC-DIG-3737",
    illustration: "digital",
    palette: {
      panel: "from-indigo-500/18 via-slate-950 to-slate-900",
      glow: "bg-indigo-400/20",
      accent: "text-indigo-300",
      border: "border-indigo-400/20",
    },
    variants: [
      { id: "neon", name: "Neon Pack", swatch: "bg-fuchsia-500", accent: "bg-pink-300" },
      { id: "mono", name: "Mono Pack", swatch: "bg-slate-100", accent: "bg-slate-300" },
    ],
    collections: ["digital", "creator", "trending"],
    tagline: "A style-ready overlay bundle for streamers and digital presenters.",
    description:
      "StreamFX includes animated stingers, lower thirds, and scene layouts so your stream looks polished instantly.",
    highlights: ["Animated transitions", "Twitch-ready layouts", "Customizable presets"],
    specs: {
      Format: "OBS / Streamlabs scenes",
      Files: "12 overlays + 2 stingers",
      Delivery: "Digital download",
      License: "Personal + commercial use",
      Support: "Setup guide",
    },
    advisory: "Install with your streaming software and replace placeholder text with your branding.",
    delivery: "Available instantly",
    reviewsList: [],
  },
  {
    id: 38,
    name: "BeatBlend Sample Kit",
    category: "Trending Digital Products",
    price: 29,
    compareAtPrice: 39,
    rating: 0,
    reviews: 0,
    badge: "Digital",
    stock: 999,
    serialNumber: "MC-DIG-3838",
    illustration: "digital",
    palette: {
      panel: "from-pink-500/16 via-slate-950 to-slate-900",
      glow: "bg-pink-300/20",
      accent: "text-pink-300",
      border: "border-pink-300/20",
    },
    variants: [
      { id: "beats", name: "Beats Pack", swatch: "bg-pink-500", accent: "bg-pink-200" },
      { id: "ambient", name: "Ambient Pack", swatch: "bg-slate-500", accent: "bg-indigo-200" },
    ],
    collections: ["digital", "creator", "new-arrivals"],
    tagline: "A polished sample kit for creators building music, podcasts, and short-form audio.",
    description:
      "BeatBlend delivers versatile loops, drum hits, and texture libraries that sound modern and ready to mix.",
    highlights: ["160+ samples", "Royalty-free", "Multi-genre"],
    specs: {
      Format: "WAV/MP3",
      Includes: "Drums + melodies + atmospheres",
      Delivery: "Digital download",
      License: "Commercial use",
      Support: "Project templates",
    },
    advisory: "Use with your DAW and layer sounds to keep mixes clean.",
    delivery: "Available instantly",
    reviewsList: [],
  },
  {
    id: 39,
    name: "FocusPro Productivity Template",
    category: "Trending Digital Products",
    price: 24,
    compareAtPrice: 34,
    rating: 0,
    reviews: 0,
    badge: "Digital",
    stock: 999,
    serialNumber: "MC-DIG-3939",
    illustration: "digital",
    palette: {
      panel: "from-green-500/16 via-slate-950 to-slate-900",
      glow: "bg-green-300/20",
      accent: "text-emerald-300",
      border: "border-emerald-300/20",
    },
    variants: [
      { id: "notion", name: "Notion Template", swatch: "bg-slate-800", accent: "bg-emerald-300" },
      { id: "figma", name: "Figma Kit", swatch: "bg-slate-100", accent: "bg-green-200" },
    ],
    collections: ["digital", "productivity", "creator"],
    tagline: "A productivity template pack for project planning and creative workflows.",
    description:
      "FocusPro includes ready-to-use boards, schedules, and resource trackers for creators, freelancers, and teams.",
    highlights: ["Task management", "Content planning", "Design-ready frames"],
    specs: {
      Format: "Notion, Figma, PDF",
      Pages: "30+ templates",
      Delivery: "Digital download",
      License: "Team-friendly",
      Support: "Setup guide",
    },
    advisory: "Customize the templates with your brand and workflow priorities.",
    delivery: "Available instantly",
    reviewsList: [],
  },
  {
    id: 40,
    name: "SparkCharge Portable Battery",
    category: "Everyday Tech Essentials",
    price: 89,
    compareAtPrice: 109,
    rating: 0,
    reviews: 0,
    badge: "Power",
    stock: 29,
    serialNumber: "MC-ESS-4040",
    illustration: "battery",
    palette: {
      panel: "from-orange-400/16 via-slate-950 to-slate-900",
      glow: "bg-orange-300/20",
      accent: "text-orange-300",
      border: "border-orange-300/20",
    },
    variants: [
      { id: "matte", name: "Matte Black", swatch: "bg-zinc-900", accent: "bg-orange-300" },
      { id: "alpine", name: "Alpine White", swatch: "bg-slate-100", accent: "bg-orange-200" },
    ],
    collections: ["everyday-tech", "mobile", "smart-gadgets"],
    tagline: "A high-speed portable battery for phones, tablets, and small devices.",
    description:
      "SparkCharge offers USB-C Power Delivery, pass-through charging, and a compact build that fits backpacks and bags.",
    highlights: ["20,000mAh battery", "65W USB-C PD", "Dual-device charging"],
    specs: {
      Capacity: "20,000mAh",
      Output: "65W USB-C + 18W USB-A",
      Charging: "USB-C input",
      Compatibility: "Laptops + phones",
      Extras: "LED power indicator",
    },
    advisory: "Recharge before travel and avoid exposure to extreme heat.",
    delivery: "Ships in 24 hours",
    reviewsList: [],
  },
  {
    id: 41,
    name: "RideReady USB Desk Fan",
    category: "Everyday Tech Essentials",
    price: 39,
    compareAtPrice: 49,
    rating: 0,
    reviews: 0,
    badge: "Essential",
    stock: 32,
    serialNumber: "MC-ESS-4141",
    illustration: "fan",
    palette: {
      panel: "from-cyan-400/16 via-slate-950 to-slate-900",
      glow: "bg-cyan-300/20",
      accent: "text-cyan-300",
      border: "border-cyan-300/20",
    },
    variants: [
      { id: "cloud", name: "Cloud White", swatch: "bg-slate-100", accent: "bg-cyan-200" },
      { id: "storm", name: "Storm Gray", swatch: "bg-zinc-800", accent: "bg-slate-200" },
    ],
    collections: ["everyday-tech", "lifestyle-tech", "mobile"],
    tagline: "A compact desk fan with quiet airflow and USB-C power.",
    description:
      "RideReady keeps workspaces cool, fits into backpacks, and runs quietly while you stay productive.",
    highlights: ["USB-C power", "Three speed modes", "Whisper-quiet operation"],
    specs: {
      Power: "USB-C 10W",
      Speeds: "3 fan modes",
      Noise: "22 dB low noise",
      Size: "130mm blade",
      Extras: "Fold-flat design",
    },
    advisory: "Keep the intake free from paper and cloth when the fan is running.",
    delivery: "Ships same day",
    reviewsList: [],
  },
  {
    id: 42,
    name: "Beacon Smart Key Finder",
    category: "Everyday Tech Essentials",
    price: 29,
    compareAtPrice: 39,
    rating: 0,
    reviews: 0,
    badge: "Portable",
    stock: 46,
    serialNumber: "MC-ESS-4242",
    illustration: "tracker",
    palette: {
      panel: "from-amber-400/16 via-slate-950 to-slate-900",
      glow: "bg-amber-300/20",
      accent: "text-amber-300",
      border: "border-amber-300/20",
    },
    variants: [
      { id: "charcoal", name: "Charcoal", swatch: "bg-zinc-900", accent: "bg-amber-300" },
      { id: "sand", name: "Sandstone", swatch: "bg-stone-300", accent: "bg-amber-200" },
    ],
    collections: ["everyday-tech", "travel", "mobile"],
    tagline: "Never lose your keys again with a slim Bluetooth finder.",
    description:
      "Beacon attaches to your keys, bag, or wallet and helps you locate them instantly from your phone.",
    highlights: ["Phone find ring", "Replaceable battery", "Compact travel-ready design"],
    specs: {
      Battery: "CR2032 replaceable",
      Range: "30 meters Bluetooth",
      Alerts: "Loud 90dB buzzer",
      Compatibility: "iOS + Android",
      Weight: "12g",
    },
    advisory: "Replace the battery every 6 months for reliable tracking.",
    delivery: "Ships in 24 hours",
    reviewsList: [],
  },
];

const categoryDescriptions = {
  "Smart Gadgets": "Compact connected tools that make everyday carry smarter.",
  "Gaming Accessories": "Performance-first gear with premium desk presence.",
  "Wireless Headphones & Audio": "Clean sound, low latency, and immersive listening.",
  "Mobile Accessories": "Fast charging and refined on-the-go essentials.",
  "Laptops & Workspace Setup": "Ergonomic upgrades for modern workstations.",
  "Smart Home Products": "Ambient, connected tech for stylish spaces.",
  "Lifestyle Tech Products": "Useful daily tech that still looks elevated.",
  "Creator & Streaming Accessories": "Tools for streaming, shooting, and editing faster.",
  "Trending Digital Products": "Instant downloads for creators and digital-first workflows.",
  "Everyday Tech Essentials": "Reliable devices for daily routines and flexible living.",
};

export const brandPartners = ["HyperPixel", "Voltware", "Auraloop", "NovaHouse", "AxisPlay", "CloudFrame"];

export const homeMetrics = [
  { value: "12K+", label: "Products explored weekly" },
  { value: "10+", label: "Curated tech categories" },
  { value: "24h", label: "Fast dispatch on core inventory" },
];

export const collectionHighlights = [
  {
    title: "Creator Control Room",
    description: "Streaming, camera, and desk tools selected for clean on-camera setups.",
    href: "/products?category=Creator+%26+Streaming+Accessories",
  },
  {
    title: "Gaming & Workspace Fusion",
    description: "Performance gear that still looks refined in a premium workstation.",
    href: "/products?collection=gaming-workspace",
  },
  {
    title: "Smart Everyday Carry",
    description: "Portable gadgets and accessories for students, creators, and commuters.",
    href: "/products?category=Smart+Gadgets",
  },
];

const unsplashPaths = {
  1: "photo-1583394838336-acd977736f90?auto=format&fit=crop&w=1200&q=80",
  2: "photo-1585386959984-a41552231658?auto=format&fit=crop&w=1200&q=80",
  3: "photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1200&q=80",
  4: "photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80",
  5: "photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
  6: "photo-1616788494672-ec7ca25fdda9?auto=format&fit=crop&w=1200&q=80",
  7: "photo-1527443195645-1133f7f28990?auto=format&fit=crop&w=1200&q=80",
  8: "photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=80",
  9: "photo-1492619375914-88005aa9e8fb?auto=format&fit=crop&w=1200&q=80",
  10: "photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1200&q=80",
  11: "photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80",
  12: "photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
  13: "photo-1537498425277-c283d32ef9db?auto=format&fit=crop&w=1200&q=80",
  14: "photo-1515863632172-fe6f5f2ce262?auto=format&fit=crop&w=1200&q=80",
  15: "photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
  16: "photo-1523475496153-3d6ccf5e93a8?auto=format&fit=crop&w=1200&q=80",
  17: "photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
  18: "photo-1512499617640-c2f9990785d6?auto=format&fit=crop&w=1200&q=80",
  19: "photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
  20: "photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
  21: "photo-1530731141654-5993c3016c77?auto=format&fit=crop&w=1200&q=80",
  22: "photo-1512058564366-c9e1e2f71f8c?auto=format&fit=crop&w=1200&q=80",
  23: "photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
  24: "photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
  25: "photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
  26: "photo-1545235618-4b5655c48575?auto=format&fit=crop&w=1200&q=80",
  27: "photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
  28: "photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&w=1200&q=80",
  29: "photo-1474631245212-32dc3c8310c6?auto=format&fit=crop&w=1200&q=80",
  30: "photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
  31: "photo-1506784242124-0f8e60a0e6d5?auto=format&fit=crop&w=1200&q=80",
  32: "photo-1519301861282-8f26f65e7618?auto=format&fit=crop&w=1200&q=80",
  33: "photo-1525382455947-f319bc05d9e4?auto=format&fit=crop&w=1200&q=80",
  34: "photo-1545233241-71c48112e9f2?auto=format&fit=crop&w=1200&q=80",
  35: "photo-1490112930942-3fa88d1a17e8?auto=format&fit=crop&w=1200&q=80",
  36: "photo-1524492412937-4961f6a2ef7c?auto=format&fit=crop&w=1200&q=80",
  37: "photo-1510511459019-5fb6481979ec?auto=format&fit=crop&w=1200&q=80",
  38: "photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1200&q=80",
  39: "photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80",
  40: "photo-1517617727270-80f9c7775b53?auto=format&fit=crop&w=1200&q=80",
  41: "photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
  42: "photo-1560807707-8cc77767d783?auto=format&fit=crop&w=1200&q=80",
};

export function getProductImageSrc(productId) {
  return `https://images.unsplash.com/${unsplashPaths[productId] ?? unsplashPaths[1]}`;
}

export function formatCurrency(value) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value);
}

export function getAllProducts() {
  return products;
}

export function getProductById(id) {
  return products.find((product) => String(product.id) === String(id)) ?? null;
}

export function getProductsByCollection(collection) {
  return products.filter((product) => product.collections.includes(collection));
}

export function getFeaturedProducts(limit = 4) {
  return getProductsByCollection("featured").slice(0, limit);
}

export function getBestSellers(limit = 4) {
  return getProductsByCollection("best-sellers").slice(0, limit);
}

export function getFlashDeals(limit = 4) {
  return getProductsByCollection("flash-deals").slice(0, limit);
}

export function getNewArrivals(limit = 4) {
  return getProductsByCollection("new-arrivals").slice(0, limit);
}

export function getTrendingProducts(limit = 4) {
  return getProductsByCollection("trending").slice(0, limit);
}

export function getGamingWorkspaceProducts(limit = 4) {
  return getProductsByCollection("gaming-workspace").slice(0, limit);
}

export function getRelatedProducts(product, limit = 4) {
  if (!product) {
    return [];
  }

  return products
    .filter((candidate) => candidate.id !== product.id)
    .sort((left, right) => {
      const leftScore = Number(left.category === product.category) + left.collections.filter((tag) => product.collections.includes(tag)).length;
      const rightScore = Number(right.category === product.category) + right.collections.filter((tag) => product.collections.includes(tag)).length;
      return rightScore - leftScore;
    })
    .slice(0, limit);
}

export function getStoreCategories() {
  return Object.entries(categoryDescriptions).map(([name, description]) => ({
    name,
    description,
    productCount: products.filter((product) => product.category === name).length,
  }));
}

export function filterProducts({ category, collection, query, sort = "featured" } = {}) {
  const normalizedQuery = query?.trim().toLowerCase();

  const filtered = products.filter((product) => {
    const matchesCategory = !category || category === "All" || product.category === category;
    const matchesCollection = !collection || collection === "all" || product.collections.includes(collection);
    const matchesQuery =
      !normalizedQuery ||
      product.name.toLowerCase().includes(normalizedQuery) ||
      product.category.toLowerCase().includes(normalizedQuery) ||
      product.tagline.toLowerCase().includes(normalizedQuery);

    return matchesCategory && matchesCollection && matchesQuery;
  });

  const sorted = [...filtered];

  switch (sort) {
    case "price-low":
      sorted.sort((left, right) => left.price - right.price);
      break;
    case "price-high":
      sorted.sort((left, right) => right.price - left.price);
      break;
    case "rating":
      sorted.sort((left, right) => right.rating - left.rating);
      break;
    case "newest":
      sorted.sort((left, right) => right.id - left.id);
      break;
    default:
      sorted.sort((left, right) => {
        const leftFeatured = left.collections.includes("featured") ? 1 : 0;
        const rightFeatured = right.collections.includes("featured") ? 1 : 0;
        return rightFeatured - leftFeatured || right.rating - left.rating;
      });
      break;
  }

  return sorted;
}

